FROM ubuntu:18.04
# Install required packages and remove the apt packages cache when done
RUN apt-get update && \
    apt-get install -y \
        git \
        openssh-client \
        iputils-ping \
        python3.6 \
        python3-pip \
        sqlite3 \
        && \
    apt-get clean && \
    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

RUN pip3 install --upgrade pip setuptools
RUN mkdir /yangsuite
RUN mkdir /ys-data
RUN mkdir /ys-static
COPY wheels/*.whl /yangsuite/
COPY setuser.sh /
RUN cd /yangsuite
RUN pip install --upgrade /yangsuite/*.whl
EXPOSE "8480"
ENV YS_DOCKER_BUILD=true
RUN yangsuite --save-settings --configure-only \
    --allowed-hosts 0.0.0.0 localhost 127.0.0.1 \
    --static-root /ys-static \
    --data-path /ys-data \
    --settings-module yangsuite.settings.production
